/* eslint-disable no-console -- CLI entry point; reporting where the file landed is the job */
// A runnable example of the report scaffolding, and the file to copy when
// starting a new PoC (Issue #2419):
//
//   pnpm report:demo               # reports/demo/index.html + artifact.html
//   pnpm report:demo --screenshot  # also rasterizes a pane through Chromium
//
// It stands in for a real before/after by rendering one model under both
// themes. A real PoC compares two code revisions instead — see
// reports/README.md, "Capturing a real before".

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { capture, dataUri, pair, pane, renderKrs, reportFragment, reportPage } from "./index.ts";

// Relative to the repo root, like the other scripts here: `pnpm report:demo`
// always runs from there.
const EXAMPLE_DIR = "examples/en/getting-started";
const OUT_DIR = "reports/demo";

/** Wraps an SVG in a document Chromium can load, so `capture` can rasterize it. */
function svgDocument(svg: string, background: string): string {
  return `<!doctype html><meta charset="utf-8">
<body style="margin:0;background:${background}">
<style>svg { width: 100%; height: auto; display: block; }</style>
${svg}`;
}

async function main(): Promise<void> {
  const source = readFileSync(join(EXAMPLE_DIR, "index.krs"), "utf8");
  const styleSource = readFileSync(join(EXAMPLE_DIR, "default.krs.style"), "utf8");

  const light = renderKrs(source, { diagramType: "system", theme: "light", styleSource });
  const dark = renderKrs(source, { diagramType: "system", theme: "dark", styleSource });

  const sections = [
    {
      title: "System view",
      body: pair(
        { label: "light theme", svg: light, background: "light", note: 'theme: "light"' },
        { label: "dark theme", svg: dark, note: 'theme: "dark"' },
        "examples/en/getting-started/index.krs, compiled twice through renderKrs().",
      ),
    },
  ];

  if (process.argv.includes("--screenshot")) {
    const [png] = await capture([
      {
        html: svgDocument(dark, "#0F172A"),
        selector: "svg",
        viewport: { width: 1280, height: 900 },
      },
    ]);
    sections.push({
      title: "Rasterized",
      body: pane({
        label: "chromium screenshot",
        image: dataUri(png),
        note: `PNG via capture(), ${Math.round(png.byteLength / 1024)} KB embedded as a data URI`,
      }),
    });
  }

  sections.push({
    title: "About this report",
    body: `<p>Generated by <code>scripts/report/demo.ts</code>. Copy it to
<code>reports/&lt;topic&gt;/build.ts</code> as the starting point for a PoC report, and read
<code>reports/README.md</code> for the convention: this directory is gitignored, so a report
never reaches a mainline PR, and a <code>spike/**</code> branch may commit one with
<code>git add -f</code>.</p>`,
  });

  const options = {
    title: "karasu report scaffolding — demo",
    lang: "en",
    subtitle: "What scripts/report/ produces, rendered from an examples/ model.",
    meta: ["scripts/report/demo.ts", "Issue #2419"],
    sections,
  };

  mkdirSync(OUT_DIR, { recursive: true });
  // Both forms, every run: index.html to open from the filesystem, artifact.html
  // to publish as a private Claude Artifact (Issue #2436). Generating them from
  // one options object is what keeps the two from describing different runs.
  const page = join(OUT_DIR, "index.html");
  const fragment = join(OUT_DIR, "artifact.html");
  writeFileSync(page, reportPage(options));
  writeFileSync(fragment, reportFragment(options));
  console.log(`wrote ${page}`);
  console.log(`wrote ${fragment} (publish this one as a Claude Artifact)`);
}

// Not top-level `await`: tsx transforms this file to CJS, where it is a syntax error.
main().catch((error: unknown) => {
  console.error(`report:demo: ${error instanceof Error ? error.message : String(error)}`);
  process.exit(1);
});
