// Browser screenshots for report generators (Issue #2419) — the other half of
// the scaffolding every PoC was rewriting. Two uses, one API: photograph the
// live app (`url`, pointed at `pnpm dev` or a preview deployment) and rasterize
// markup that only exists in the generator (`html`).
//
// Chromium comes from packages/e2e's Playwright install, so it is shared with
// the E2E suite rather than downloaded again:
//   pnpm --filter @karasu-tools/e2e install-browsers
//
// Managing a dev server is out of scope on purpose. A report is generated by
// hand, and `pnpm dev` in another terminal is both simpler and easier to debug
// than a lifecycle this module would have to own.

import { chromium } from "@playwright/test";

export interface Viewport {
  width: number;
  height: number;
}

/** One screenshot to take. Pass exactly one of `url` / `html`. */
export interface ShotSpec {
  /** Page to load, e.g. "http://localhost:5173/?file=index.krs". */
  url?: string;
  /** Self-contained markup to render offline — SVG wrapped in a document, say. */
  html?: string;
  /** Clip to this element instead of shooting the viewport. */
  selector?: string;
  /** Shoot the full scrollable page. Ignored when `selector` is set. */
  fullPage?: boolean;
  /** Overrides the capture-wide viewport. */
  viewport?: Viewport;
  /** Settle time after load, for layout or transitions that finish late. */
  settleMs?: number;
}

export interface CaptureOptions {
  /** Applied to every spec that does not override it. Defaults to 1280x800. */
  viewport?: Viewport;
  /** 2 gives retina-sharp PNGs, at 4x the bytes. Defaults to 2. */
  deviceScaleFactor?: number;
  /** The app renders `system` theme via prefers-color-scheme. Defaults to "dark". */
  colorScheme?: "dark" | "light";
  /** How long a single shot may take, in ms. Defaults to 30s. */
  timeoutMs?: number;
}

const DEFAULT_VIEWPORT: Viewport = { width: 1280, height: 800 };

/**
 * Takes the screenshots in order and returns their PNG bytes, one buffer per
 * spec — feed them to `dataUri()` to embed them in the report. A single browser
 * serves the whole batch and is always closed.
 */
export async function capture(
  specs: readonly ShotSpec[],
  options: CaptureOptions = {},
): Promise<Buffer[]> {
  const {
    viewport = DEFAULT_VIEWPORT,
    deviceScaleFactor = 2,
    colorScheme = "dark",
    timeoutMs = 30_000,
  } = options;

  const browser = await chromium.launch().catch((error: unknown) => {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(
      `capture: could not launch Chromium. Install it with\n` +
        `  pnpm --filter @karasu-tools/e2e install-browsers\n` +
        message,
    );
  });

  try {
    const shots: Buffer[] = [];
    for (const spec of specs) {
      if ((spec.url === undefined) === (spec.html === undefined)) {
        throw new Error("capture: pass exactly one of `url` or `html`");
      }
      const context = await browser.newContext({
        viewport: spec.viewport ?? viewport,
        deviceScaleFactor,
        colorScheme,
      });
      try {
        const page = await context.newPage();
        page.setDefaultTimeout(timeoutMs);
        if (spec.url !== undefined) {
          await page.goto(spec.url, { waitUntil: "networkidle" });
        } else {
          await page.setContent(spec.html ?? "", { waitUntil: "load" });
        }
        if (spec.settleMs) await page.waitForTimeout(spec.settleMs);
        if (spec.selector === undefined) {
          shots.push(await page.screenshot({ fullPage: spec.fullPage }));
        } else {
          shots.push(await page.locator(spec.selector).screenshot());
        }
      } finally {
        await context.close();
      }
    }
    return shots;
  } finally {
    await browser.close();
  }
}
