/**
 * Delivering a generated model by opening a pull request.
 *
 * This is the ratchet (#2228, ADR-1990 decision 4). A progress page or an
 * email would deliver the same bytes and leave the corrections nowhere: a
 * human who fixes a wrong boundary in a web view has fixed it for nobody. A
 * pull request puts the document where ADR-1829 says the record belongs and
 * where ADR-2249's permalink surface already reads from, so a correction is
 * made once and is then the thing everyone sees.
 *
 * It also costs no personal data. There is no email address to collect, and
 * GitHub's own notifications carry the "it is ready" message — which is what
 * makes a 12-19 minute latency stop mattering (#2262).
 *
 * **This needs `contents:write` and `pull_requests:write`,** which is more
 * than the `contents:read` that ADR-1990 decision 6 scoped the install
 * consent to. Widening what the App may do to someone's repository without
 * their having agreed to it is not a thing to do quietly, so delivery is
 * **off unless a deploy turns it on**, and #1996 owns the consent copy that
 * makes turning it on legitimate. The switch is checked by the caller; this
 * module is the mechanism, not the policy.
 */
import { GitHubApiError, type GitHubClient } from "../github/client.js";

export interface DeliveryInput {
  installationId: string;
  owner: string;
  repo: string;
  /** The commit the model was generated from. */
  sha: string;
  /** The generated document. Already structure-scanned by the pipeline. */
  krs: string;
  /** Domains the reverse identified, for the pull-request body. */
  domains: { name: string; summary: string; confidence?: string }[];
  /** How many redactions fired on the way in. Counts only, never values. */
  redactions: number;
}

export interface DeliveryResult {
  number: number;
  url: string;
  /** False when an open pull request was already there for this commit. */
  created: boolean;
  branch: string;
  path: string;
}

export class DeliveryFailed extends Error {
  constructor(message: string) {
    super(message);
    this.name = "DeliveryFailed";
  }
}

/**
 * Where the document lands.
 *
 * `docs/` because that is where a reader looks, and a fixed name because the
 * point of the ratchet is that the next reverse finds the corrected version
 * in a predictable place. A repository that wants it elsewhere moves the file
 * in the pull request, which is a correction like any other.
 */
export const KRS_PATH = "docs/architecture.krs";

/**
 * One branch per commit.
 *
 * Deriving the name from the commit is what makes re-generating the same SHA
 * idempotent: the branch is already there, the file already matches, and the
 * open pull request is found rather than duplicated. A timestamp or a counter
 * here would open a second pull request for the same content every time
 * anyone re-asked.
 */
export function deliveryBranch(sha: string): string {
  return `karasu-nest/model-${sha.slice(0, 12)}`;
}

/** The pull-request body. Says what it is, how sure it is, and how to fix it. */
export function pullRequestBody(input: DeliveryInput): string {
  const confidence = input.domains
    .map(
      (domain) =>
        `| ${domain.name} | ${domain.confidence ?? "unstated"} | ${domain.summary.replaceAll("|", "\\|")} |`,
    )
    .join("\n");

  return [
    `This is a generated architecture model of \`${input.owner}/${input.repo}\` at ${input.sha.slice(0, 7)}.`,
    "",
    "**It is a first draft, not a description of what you built.** karasu-nest read the",
    "repository and guessed at the boundaries; nodes it was unsure about carry `@draft`.",
    "The useful thing to do with it is disagree with it: correcting a boundary here is a",
    "correction everyone downstream sees, because this file is the record.",
    "",
    "## What it thinks your domains are",
    "",
    "| Domain | Confidence | Summary |",
    "| --- | --- | --- |",
    confidence.length === 0 ? "| (none identified) | | |" : confidence,
    "",
    "## How to correct it",
    "",
    `- Edit \`${KRS_PATH}\` in this branch. The syntax reference is at https://kompiro.github.io/karasu/spec/syntax`,
    "- Remove `@draft` from anything you have confirmed",
    "- Merge when it is right, or close this pull request if the model is not useful",
    "",
    "## What was read",
    "",
    `- Source files were read at ${input.sha.slice(0, 7)} and were **not** stored. Only this document was kept.`,
    input.redactions === 0
      ? "- No credential-shaped strings were found in the source."
      : `- ${input.redactions} credential-shaped string(s) were redacted before anything reached the model.`,
    "",
    "<sub>Generated by [karasu-nest](https://github.com/kompiro/karasu). Uninstalling the App deletes everything it kept.</sub>",
  ].join("\n");
}

export interface DeliveryDeps {
  github: GitHubClient;
}

/**
 * Open (or find) the pull request carrying a generated model.
 *
 * Idempotent by commit: called twice for the same SHA, the second call
 * returns the first call's pull request rather than opening another. That is
 * a requirement rather than a nicety — the generation route can dispatch a
 * retry after a failure, and a repository owner who finds three identical
 * pull requests has been given a reason to uninstall.
 */
export async function deliverPullRequest(
  input: DeliveryInput,
  deps: DeliveryDeps,
): Promise<DeliveryResult> {
  const { github } = deps;
  const { installationId, owner, repo, sha } = input;
  const branch = deliveryBranch(sha);
  const ref = `heads/${branch}`;

  // An open pull request for this commit is the whole answer. Checked first
  // so a re-delivery costs one request rather than a branch write.
  const existing = await github.openPullRequest(installationId, owner, repo, branch);
  if (existing !== undefined) {
    return { ...existing, created: false, branch, path: KRS_PATH };
  }

  const base = await github.defaultBranch(installationId, owner, repo);

  // The branch may exist from a delivery whose pull request was closed, or
  // from one that died between the two steps. Reusing it is right in both
  // cases: the content is keyed on the same commit.
  if ((await github.refSha(installationId, owner, repo, ref)) === undefined) {
    try {
      await github.createRef(installationId, owner, repo, ref, sha);
    } catch (cause) {
      // A 422 here is almost always "reference already exists", which means
      // someone else created it between the check and the write. That is the
      // state we wanted.
      if (!(cause instanceof GitHubApiError) || cause.status !== 422) throw cause;
    }
  }

  const currentFile = await github.fileSha(installationId, owner, repo, KRS_PATH, branch);
  await github.putFile(installationId, owner, repo, {
    path: KRS_PATH,
    content: input.krs,
    message: `docs: add a generated architecture model for ${sha.slice(0, 7)}`,
    branch,
    ...(currentFile === undefined ? {} : { sha: currentFile }),
  });

  const created = await github.createPullRequest(installationId, owner, repo, {
    title: `docs: generated architecture model (${sha.slice(0, 7)})`,
    head: branch,
    base,
    body: pullRequestBody(input),
  });
  return { ...created, created: true, branch, path: KRS_PATH };
}
