import { basename } from "node:path";
import { effectiveSet, loadParsed } from "./extractor.ts";
import type { ParsedAdr } from "./validator.ts";
import { listTopics, renderOverview, renderTopicMarkdown } from "./visualizer.ts";

interface GeneratedFile {
  /** Path relative to the ADR dir (e.g. "graph.md", "graph/parser.md"). */
  relativePath: string;
  contents: string;
}

/**
 * Group effective ADRs by topic and render a Markdown summary. This is the
 * single file that CLAUDE.md (and any AI context pipeline) should reference
 * instead of scanning the whole `docs/adr/` directory.
 */
function renderEffective(adrs: ParsedAdr[]): string {
  const effective = effectiveSet(adrs);
  const byTopic = new Map<string, ParsedAdr[]>();
  for (const p of effective) {
    if (!byTopic.has(p.fm.topic)) byTopic.set(p.fm.topic, []);
    byTopic.get(p.fm.topic)!.push(p);
  }
  const sortedTopics = [...byTopic.keys()].sort();

  const lines: string[] = [
    "# Effective ADR Set",
    "",
    `Auto-generated by \`pnpm adr:regenerate\`. ${effective.length} of ${adrs.length} ADRs are currently \`status: accepted\` with no \`superseded_by\`.`,
    "",
    "Consumers (e.g. AI context pipelines) should read this file instead of scanning `docs/adr/` directly — it pre-filters out superseded, deprecated, and not-adopted ADRs.",
    "",
    "See also: [dependency graph](graph.md), per-topic detail under [graph/](graph/).",
    "",
  ];

  for (const topic of sortedTopics) {
    lines.push(`## ${topic}`);
    lines.push("");
    const items = [...byTopic.get(topic)!].sort((a, b) => a.id.localeCompare(b.id));
    for (const p of items) {
      const filename = basename(p.file);
      lines.push(`- [${p.id}](${filename}) — ${p.fm.title}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

/**
 * Compute every file the ADR tooling expects to keep in sync under
 * `docs/adr/`. The caller either writes them to disk (`regenerate`) or
 * compares them against disk state (`check`).
 */
export function buildGeneratedFiles(adrs: ParsedAdr[]): GeneratedFile[] {
  const files: GeneratedFile[] = [
    { relativePath: "effective.md", contents: renderEffective(adrs) },
    { relativePath: "graph.md", contents: renderOverview(adrs) },
  ];
  for (const topic of listTopics(adrs)) {
    files.push({
      relativePath: `graph/${topic}.md`,
      contents: renderTopicMarkdown(adrs, topic),
    });
  }
  return files;
}

export function loadAdrs(dir: string): ParsedAdr[] {
  return loadParsed(dir);
}
