#!/usr/bin/env tsx
// Generate `THIRD_PARTY_NOTICES.md` for one or more publishable packages, listing
// every production dependency with its version, SPDX license, and the full text of
// its LICENSE file. MIT and Apache-2.0 both require redistributing the upstream
// LICENSE text when their code ships in our artifacts (most relevant for
// `packages/vscode`, whose deps are esbuild-bundled into the `.vsix`).
//
// Usage: tsx scripts/ci/generate-third-party-notices.ts <packageDir> [<packageDir> ...]
// Wired into each publishable package's `build` script; the output is git-ignored.
//
// See `docs/design/license-compliance-automation.md`.

import { execFileSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import type { PnpmLicensesList } from "./license-allowlist.ts";

export interface DependencyNotice {
  name: string;
  version: string;
  license: string;
  /** Full LICENSE file text, or `null` if no license file was found in the package. */
  licenseText: string | null;
}

const LICENSE_FILE_PATTERN = /^(LICEN[CS]E|COPYING|NOTICE)(\.\w+)?$/i;

/** Find and read the upstream LICENSE-like file in a package directory, if any. */
export function readLicenseFile(packagePath: string): string | null {
  let entries: string[];
  try {
    entries = readdirSync(packagePath);
  } catch {
    return null;
  }
  // Prefer a plain "LICENSE" over "LICENSE.md" / "COPYING" / "NOTICE" for stable output.
  const matches = entries
    .filter((name) => LICENSE_FILE_PATTERN.test(name))
    .sort((a, b) => rank(a) - rank(b) || a.localeCompare(b));
  for (const name of matches) {
    try {
      const text = readFileSync(join(packagePath, name), "utf8").trim();
      if (text.length > 0) return text;
    } catch {
      // unreadable — try the next candidate
    }
  }
  return null;
}

function rank(fileName: string): number {
  const lower = fileName.toLowerCase();
  if (lower === "license") return 0;
  if (lower.startsWith("license")) return 1;
  if (lower.startsWith("licence")) return 2;
  if (lower.startsWith("copying")) return 3;
  return 4; // NOTICE and anything else last
}

function collectNotices(packageName: string): DependencyNotice[] {
  let stdout: string;
  try {
    stdout = execFileSync(
      "pnpm",
      ["--filter", packageName, "licenses", "list", "--prod", "--json"],
      {
        encoding: "utf8",
        maxBuffer: 64 * 1024 * 1024,
      },
    );
  } catch (error) {
    const stdoutOnError = (error as { stdout?: string | Buffer }).stdout;
    if (stdoutOnError === undefined) throw error;
    stdout = stdoutOnError.toString("utf8");
  }
  const trimmed = stdout.trim();
  const licenses = (trimmed === "" ? {} : JSON.parse(trimmed)) as PnpmLicensesList;

  const notices: DependencyNotice[] = [];
  for (const [license, packages] of Object.entries(licenses)) {
    for (const pkg of packages) {
      // Skip workspace-internal packages — they ship under the repo's own LICENSE.
      if (pkg.name.startsWith("@karasu-tools/")) continue;
      pkg.versions.forEach((version, index) => {
        const path = pkg.paths[index] ?? pkg.paths[0];
        notices.push({
          name: pkg.name,
          version,
          license,
          licenseText: path !== undefined ? readLicenseFile(path) : null,
        });
      });
    }
  }
  return notices.sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));
}

export function renderNotices(packageName: string, notices: DependencyNotice[]): string {
  const lines: string[] = [
    `# Third-Party Notices`,
    ``,
    `This file lists the third-party production dependencies redistributed with`,
    `\`${packageName}\` and the text of their licenses. It is generated by`,
    `\`scripts/ci/generate-third-party-notices.ts\` during the package build — do not edit by hand.`,
    ``,
  ];
  if (notices.length === 0) {
    lines.push(`_No third-party production dependencies._`, ``);
    return lines.join("\n");
  }
  for (const notice of notices) {
    lines.push(`## ${notice.name}@${notice.version}`, ``, `License: ${notice.license}`, ``);
    if (notice.licenseText === null) {
      lines.push(`_No license file was found in this package; see the SPDX identifier above._`, ``);
    } else {
      lines.push("```", notice.licenseText, "```", ``);
    }
  }
  return lines.join("\n");
}

function packageNameOf(packageDir: string): string {
  const manifest = join(packageDir, "package.json");
  if (existsSync(manifest)) {
    const parsed = JSON.parse(readFileSync(manifest, "utf8")) as { name?: string };
    if (typeof parsed.name === "string" && parsed.name.length > 0) return parsed.name;
  }
  return basename(resolve(packageDir));
}

function main(argv: string[]): void {
  const dirs = argv.slice(2);
  if (dirs.length === 0) {
    process.stderr.write(
      "usage: tsx scripts/ci/generate-third-party-notices.ts <packageDir> [<packageDir> ...]\n",
    );
    process.exitCode = 1;
    return;
  }
  for (const dir of dirs) {
    const packageDir = resolve(dir);
    const packageName = packageNameOf(packageDir);
    const notices = collectNotices(packageName);
    const outPath = join(packageDir, "THIRD_PARTY_NOTICES.md");
    writeFileSync(outPath, renderNotices(packageName, notices));
    process.stdout.write(
      `Wrote ${outPath} (${notices.length} dependenc${notices.length === 1 ? "y" : "ies"}).\n`,
    );
  }
}

// Only run when invoked directly (not when imported by tests).
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main(process.argv);
}
