import { describe, expect, it } from "vitest";
import { resolve } from "node:path";
import { DOCS_SITE_ROUTES } from "../../packages/app/src/utils/docs-site-links.ts";
import { check, publishedRoutes, unownedUrlLiterals, URL_OWNER } from "./reference-docs-links.ts";

const REPO_ROOT = resolve(import.meta.dirname, "../..");

describe("publishedRoutes", () => {
  it("covers the guide pages and the generated gallery in both locales", () => {
    const routes = publishedRoutes();
    expect(routes).toContain("guide/");
    expect(routes).toContain("ja/guide/");
    expect(routes).toContain("guide/notation-cookbook/");
    expect(routes).toContain("ja/guide/notation-cookbook/");
    // Generated by sync.ts rather than synced from docs/, so it has no .ja.md
    // sibling to key off — both locales exist unconditionally.
    expect(routes).toContain("examples/");
    expect(routes).toContain("ja/examples/");
    expect(routes).toContain("examples/getting-started/");
  });

  it("does not invent routes for pages the site does not publish", () => {
    const routes = publishedRoutes();
    // A real doc, deliberately outside PUBLISHED_EN_FILES.
    expect(routes).not.toContain("guide/reverse-engineering-with-ai/");
    expect(routes).not.toContain("roadmap/");
  });
});

describe("check", () => {
  it("passes for the signpost routes the app ships", () => {
    expect(check(REPO_ROOT)).toEqual([]);
  });

  it("rejects a route that is not a published page", () => {
    const problems = check(REPO_ROOT, { guide: "guide/does-not-exist/" });
    expect(problems).toHaveLength(1);
    expect(problems[0].message).toContain("not a published docs-site page in: en, ja");
  });

  it("rejects a route whose en page is published but whose ja page is not", () => {
    // Every published doc happens to have a .ja.md sibling today, so the
    // half-translated case is injected: the ja link would 404 while the en one
    // resolves, and only the ja half may be reported.
    const problems = check(REPO_ROOT, { guide: "guide/" }, new Set(["guide/"]));
    expect(problems).toHaveLength(1);
    expect(problems[0].message).toContain("not a published docs-site page in: ja");
  });

  it("rejects a #fragment even when the page itself is published", () => {
    const problems = check(REPO_ROOT, {
      cookbook: "guide/notation-cookbook/#1-keyvalue-store-redis-etcd--a-leaf-less-database",
    });
    expect(problems).toHaveLength(1);
    expect(problems[0].message).toContain("#fragment");
  });

  it("sends a broken gallery route to GALLERY_PAGES, not to PUBLISHED_EN_FILES", () => {
    // The gallery is generated from the manifest, so the remediation for a
    // stale slug has to name the manifest — adding an `examples/` entry to
    // PUBLISHED_EN_FILES would do nothing.
    const [problem] = check(REPO_ROOT, { examples: "examples/renamed-away/" });
    expect(problem.message).toContain("GALLERY_PAGES");
    expect(problem.message).not.toContain("PUBLISHED_EN_FILES");
  });

  it("sends a broken docs route to PUBLISHED_EN_FILES", () => {
    const [problem] = check(REPO_ROOT, { guide: "guide/gone/" });
    expect(problem.message).toContain("PUBLISHED_EN_FILES");
    expect(problem.message).not.toContain("GALLERY_PAGES");
  });
});

describe("unownedUrlLiterals", () => {
  it("finds no app module spelling the docs-site URL besides its owner", () => {
    expect(unownedUrlLiterals(REPO_ROOT)).toEqual([]);
  });

  it("would report a module that pasted the URL in (negative control)", () => {
    // Withdraw the owner's exemption: the one file that legitimately spells the
    // host must then be reported, proving the scan reads app sources at all.
    expect(unownedUrlLiterals(REPO_ROOT, "packages/app/src/not-the-owner.ts")).toEqual([URL_OWNER]);
  });
});

describe("DOCS_SITE_ROUTES", () => {
  it("keeps the base-relative shape routeOf() produces", () => {
    for (const route of Object.values(DOCS_SITE_ROUTES)) {
      expect(route.startsWith("/")).toBe(false);
      expect(route.endsWith("/")).toBe(true);
    }
  });
});
